### ISSUE TITLE
when POCS requests a slew that the mount must go through the meridian, the next state starts before the long slew is complete

### ISSUE THREAD

**Issue by lspitler** [AstroHuntsman/POCS#11]

**Comment by wtgee** [comment]
I think this is fixed with the latest series of commits. Essentially we were interrupting during observing and focusing but that wasn't stopping the cameras and the system was getting confused. We now one reschedule after `analyzing` no matter what. This means that if an interrupt comes through right at the beginning of `focusing`, we will continue to focus, then go `observing`, then `analyzing`, then at the end of `analyzing` go to `scheduling`. We can revisit that logic later but it should be okay for now.

Closing this issue until we experience it again.
